In [3]:
import pandas as pd

In [4]:
import numpy as np

In [8]:
ran_arr = np.random.randint(1,10,(5,5))

In [9]:
ran_arr

array([[3, 2, 7, 5, 9],
       [1, 5, 2, 3, 9],
       [7, 5, 9, 7, 8],
       [5, 5, 9, 2, 4],
       [4, 8, 5, 6, 8]], dtype=int32)

In [12]:
ran_arr.dtype

dtype('int32')

In [14]:
identity_matrix  = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock

print(f"Size: {retail_data.size}")
print(f"Dimention: {retail_data.ndim}")
print(f"Memory size: {retail_data.nbytes}")

Size: 50
Dimention: 2
Memory size: 400


In [22]:
retail_data[0,:]

array([1001.  ,   29.99,   45.  ,    4.2 ,   15.  ])

In [25]:
retail_data[-1]

array([1010.  ,   59.99,   34.  ,    4.4 ,   10.  ])

In [24]:
retail_data[:,1]

array([29.99, 49.99, 19.99, 89.99, 15.99, 69.99, 39.99, 79.99, 25.99,
       59.99])

In [29]:
correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0][1]
print(f"Correlation: {correlation:.4f}")

Correlation: -0.9291


In [31]:
reshaped_5x10 = retail_data.reshape(10, 5)
print(reshaped_5x10)

[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [32]:
retail_data.T

array([[1001.  , 1002.  , 1003.  , 1004.  , 1005.  , 1006.  , 1007.  ,
        1008.  , 1009.  , 1010.  ],
       [  29.99,   49.99,   19.99,   89.99,   15.99,   69.99,   39.99,
          79.99,   25.99,   59.99],
       [  45.  ,   32.  ,   78.  ,   12.  ,   95.  ,   28.  ,   56.  ,
          18.  ,   67.  ,   34.  ],
       [   4.2 ,    4.5 ,    3.8 ,    4.7 ,    4.  ,    4.3 ,    3.9 ,
           4.6 ,    4.1 ,    4.4 ],
       [  15.  ,    8.  ,   22.  ,    5.  ,   18.  ,   12.  ,   20.  ,
           7.  ,   16.  ,   10.  ]])

In [33]:
split_vertical = np.vsplit(retail_data, 2)
print("First part:")
print(split_vertical[0])
print("\nSecond part:")
print(split_vertical[1])

First part:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]]

Second part:
[[1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]


In [34]:
split_horizontal = np.hsplit(retail_data, 2)
print("First part:")
print(split_horizontal[0])
print("\nSecond part:")
print(split_horizontal[1])

ValueError: array split does not result in an equal division

In [37]:
popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)

[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]
