In [1]:
import numpy as np

In [2]:
# Question 1: Array Creation and Manipulation
# Q1.1: Create a 4x4 identity matrix using np.eye()

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# By default it is float, if we want in int then.... 
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [4]:
# Q1.2: Create an array of 8 zeros using np.zeros()
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# To check shape and data type 
print(f"shape: {np.zeros(8).shape}")
print(f"shape: {np.zeros(8).dtype}")

shape: (8,)
shape: float64


In [6]:
np.zeros(8,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Q1.3: Create an array of 6 ones using np.ones()
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()

# NOTE: I typed as "arrange" but it's "arange"! Remember this. 

# General form: np.arange(start, stop, step), where stop is exclusive.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [ ]:
# NOTES to self: 

# Use linspace when you know how many points you want between two values (endpoints included by default).
# Use arange when you know the step size and don’t need the endpoint included.

# If we don’t want to include the endpoint with linspace, use endpoint=False.

# pretty-print NumPy arrays to two decimal places
arr = np.linspace(0, 50, 8)
pretty_arr = np.round(arr, 2)
print(pretty_arr)

# OR using list comprehension & string formatting
arr = np.linspace(0, 60, 8)
pretty_list = [f"{x:.2f}" for x in arr]
print(pretty_list) # it will give o/p in string because of f string

[ 0.    7.14 14.29 21.43 28.57 35.71 42.86 50.  ]
['0.00', '8.57', '17.14', '25.71', '34.29', '42.86', '51.43', '60.00']


In [ ]:
# creating banking data array first

# np.random.randint(101,10000,(10,5))

banking_data = np.array([
     [101, 5000, 720, 45, 5],
    [102, 1500, 680, 20, 2],
    [103, 2500, 700, 30, 3],
    [104, 8000, 750, 60, 8],
    [105, 3000, 710, 25, 4],
    [106, 10000, 780, 80, 10],
    [107, 1200, 650, 15, 1],
    [108, 4000, 730, 40, 6],
    [109, 3500, 690, 28, 3],
    [110, 9000, 770, 75, 9]
])
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
print(banking_data)

[[  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]]


In [15]:
# Question 2: Array Attributes and Information

# Q2.1: What is the shape of the banking_data array?
banking_data_shape = banking_data.shape
print(banking_data_shape)

(10, 5)


In [16]:
# Q2.2: What is the data type of the banking_data array?
banking_data_datatype = banking_data.dtype
print(banking_data_datatype)

int64


In [17]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
banking_data_size = banking_data.size
print(banking_data_size)

50


In [18]:
# Q2.4: What is the number of dimensions of the banking_data array?
banking_data_dim = banking_data.ndim
print(banking_data_dim)

2


In [21]:
# Q2.5: What is the memory size of the banking_data array in bytes?
banking_data_bytes = banking_data.nbytes
print(banking_data_bytes)

400


In [ ]:
# NOTES to self :

# In Python, things that describe an object (properties) are usually implemented as attributes, not functions.

# so shape, dtype, ndim, nbytes don't have parethesis as they are attributes not methods. 

# to check if its method or attribute -> use callable method
# ex. print(callable(arr.shape)) , print(callable(arr.reshape)) 
# if True then method, False then attr

# OR use type() to see what it actually is

In [ ]:
# Question 3: Indexing and Slicing
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)

# Q3.1: Extract the first row of banking_data

banking_data_first_row = banking_data[0] # banking_data[0,:]
print(banking_data_first_row)

[ 101 5000  720   45    5]


In [24]:
# Q3.2: Extract the last row of banking_data
banking_data_last_row = banking_data[-1]
print(banking_data_last_row)


[ 110 9000  770   75    9]


In [25]:
# Q3.3: Extract the Account_Balance column (column index 1)
banking_data_Account_Balance = banking_data[:,1]
print(banking_data_Account_Balance)


[ 5000  1500  2500  8000  3000 10000  1200  4000  3500  9000]


In [ ]:
# Q3.4: Extract the first 4 rows and first 3 columns
banking_data_r4_c3 = banking_data[:4,:3] # banking_data[0:4, 0:3]
print(banking_data_r4_c3)

[[ 101 5000  720]
 [ 102 1500  680]
 [ 103 2500  700]
 [ 104 8000  750]]


In [29]:
# Q3.5: Extract rows 3 to 7 (inclusive)
banking_data_r3_7 = banking_data[3:8,:]
print(banking_data_r3_7)

[[  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]]


In [30]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 4: Mathematical Operations

# Q4.1: Calculate the sum of all account balances

sum_acc_balance = banking_data[:,1].sum()
print(sum_acc_balance)


47700


In [31]:
# Q4.2: Calculate the mean account balance
mean_acc_balance = banking_data[:,1].mean()
print(mean_acc_balance)

4770.0


In [ ]:
# Q4.3: Calculate the standard deviation of account balances

# NOTES: 
# Standard deviation measures how spread out the values are from the mean.
# High std → more spread; low std → values are closer to mean.

std_acc_balance = banking_data[:,1].std()
print(std_acc_balance)

2994.3446695395637


In [36]:
# Q4.4: Calculate the variance of account balances

# NOTES  :
# Variance = square of standard deviation.
# Measures spread in squared units.

variance_acc_balance = banking_data[:,1].var()
print(variance_acc_balance)

8966100.0


In [ ]:
# Q4.5: Calculate the median account balance

# median isn’t an instance method — it’s a standalone NumPy function.

# So this code gives error -> 'numpy.ndarray' object has no attribute 'median'
# median_acc_balance = banking_data[:,1].median()

# NOTES: 
# Median = middle value when data is sorted.
# If even number of values → average of the two middle numbers.

median_acc_balance = np.median(banking_data[:,1])
print(median_acc_balance)

3750.0


In [40]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 5: Statistical Functions

# Q5.1: Find the minimum and maximum account balances
min_acc_bal = banking_data[:,1].min()
print(min_acc_bal)
max_acc_bal = banking_data[:,1].max()
print(max_acc_bal)

1200
10000


In [42]:
#Q5.2: Find the minimum and maximum credit scores
min_credit_score = banking_data[:,2].min()
print(min_credit_score)
max_credit_score = banking_data[:,2].max()
print(max_credit_score)

650
780


In [43]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
perc_value_acc_bal = np.percentile(banking_data[:,1],[25,50,75])
print(perc_value_acc_bal)

[2625. 3750. 7250.]


In [48]:
# Q5.4: Calculate the correlation between account balance and credit score
acc_bal_data = banking_data[:,1] 
cred_score_data = banking_data[:,2]

# np.corrcoef returns a 2x2 matrix; the [0, 1] value is the actual correlation coefficient.
np.corrcoef(acc_bal_data,cred_score_data)[0,1]

np.float64(0.9466761610274407)

In [51]:
# Q5.5: Calculate the covariance between account balance and credit score
np.round(np.cov(acc_bal_data,cred_score_data)[0,1],2)


np.float64(121822.22)

In [53]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 6: Array Reshaping and Manipulation

# Q6.1: Reshape the banking_data to 5 rows × 10 columns
#np.reshape(banking_data,(5,10))
banking_data.reshape(5,10)

array([[  101,  5000,   720,    45,     5,   102,  1500,   680,    20,
            2],
       [  103,  2500,   700,    30,     3,   104,  8000,   750,    60,
            8],
       [  105,  3000,   710,    25,     4,   106, 10000,   780,    80,
           10],
       [  107,  1200,   650,    15,     1,   108,  4000,   730,    40,
            6],
       [  109,  3500,   690,    28,     3,   110,  9000,   770,    75,
            9]])

In [54]:
# Q6.2: Flatten the banking_data to a 1D array
banking_data.flatten()

array([  101,  5000,   720,    45,     5,   102,  1500,   680,    20,
           2,   103,  2500,   700,    30,     3,   104,  8000,   750,
          60,     8,   105,  3000,   710,    25,     4,   106, 10000,
         780,    80,    10,   107,  1200,   650,    15,     1,   108,
        4000,   730,    40,     6,   109,  3500,   690,    28,     3,
         110,  9000,   770,    75,     9])

In [61]:
# Q6.3: Transpose the banking_data
banking_data.T

array([[  101,   102,   103,   104,   105,   106,   107,   108,   109,
          110],
       [ 5000,  1500,  2500,  8000,  3000, 10000,  1200,  4000,  3500,
         9000],
       [  720,   680,   700,   750,   710,   780,   650,   730,   690,
          770],
       [   45,    20,    30,    60,    25,    80,    15,    40,    28,
           75],
       [    5,     2,     3,     8,     4,    10,     1,     6,     3,
            9]])

In [63]:
# Q6.4: Split the banking_data into 2 equal parts vertically
np.vsplit(banking_data,2)

[array([[ 101, 5000,  720,   45,    5],
        [ 102, 1500,  680,   20,    2],
        [ 103, 2500,  700,   30,    3],
        [ 104, 8000,  750,   60,    8],
        [ 105, 3000,  710,   25,    4]]),
 array([[  106, 10000,   780,    80,    10],
        [  107,  1200,   650,    15,     1],
        [  108,  4000,   730,    40,     6],
        [  109,  3500,   690,    28,     3],
        [  110,  9000,   770,    75,     9]])]

In [64]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
np.hsplit(banking_data,2)

ValueError: array split does not result in an equal division

In [ ]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 7: Logical Operations and Filtering

# Q7.1: Find customers with account balance greater than $100,000
customers_grt_1L = banking_data[banking_data[:,1] > 10000,0]
# customers_grt_1L = banking_data[banking_data[:,1] > 7000,0]
print(customers_grt_1L)

[]


In [72]:
# Q7.2: Find customers with credit score greater than 800
customers_cred_grt_800 = banking_data[banking_data[:,2] > 800,0]
# customers_cred_grt_800 = banking_data[banking_data[:,2] > 700,0]
print(customers_cred_grt_800)

[]


In [75]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
customers3 = banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750),0]
print(customers3)

[]


In [81]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
customers4 = np.sum(( banking_data[:,1] > 8000) &  (banking_data[:,1] < 100000))
print(customers4)


2


In [ ]:
# Q7.5: Find the index of the customer with the highest credit score
customers5 = banking_data[:,2].argmax() + 1
print(customers5)

6


In [ ]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 8: Sorting and Searching

# Q8.1: Sort the banking_data by account balance (ascending)

sorted_bank_data_by_acc_bal = banking_data[:,1].sort()

NameError: name 'banking_data' is not defined

In [7]:
import numpy as np
banking_data = np.array([
     [101, 5000, 720, 45, 5],
    [102, 1500, 680, 20, 2],
    [103, 2500, 700, 30, 3],
    [104, 8000, 750, 60, 8],
    [105, 3000, 710, 25, 4],
    [106, 10000, 780, 80, 10],
    [107, 1200, 650, 15, 1],
    [108, 4000, 730, 40, 6],
    [109, 3500, 690, 28, 3],
    [110, 9000, 770, 75, 9]
])

In [ ]:
sorted_bank_data_by_acc_bal = banking_data[:,1].sort()
print(sorted_bank_data_by_acc_bal)

# NOTES to self:

# sort() either returns sorted values of a 1-D array or sorts each row/column independently in a 2-D array
# Use argsort() when you want to reorder whole rows (or multiple aligned arrays) based on one column

# np.argsort(a)
# Returns the indices (a permutation) that would sort a.
# You use those indices to reindex your original 2-D array so entire rows move together.


None


In [8]:
# Correct way to sort by column and reorder all rows
order = banking_data[:,1].argsort()
sorted_by_bal = banking_data[order]
print(sorted_by_bal)

[[  107  1200   650    15     1]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  105  3000   710    25     4]
 [  109  3500   690    28     3]
 [  108  4000   730    40     6]
 [  101  5000   720    45     5]
 [  104  8000   750    60     8]
 [  110  9000   770    75     9]
 [  106 10000   780    80    10]]


In [12]:
# Q8.2: Sort the banking_data by credit score (descending)
order2 = banking_data[:,2].argsort()[::-1]
# [::-1] when step is <0 (negative) , start is end and stop is beginning, -1 means go backward 
sorted_by_credit_score = banking_data[order2]
print(sorted_by_credit_score)

[[  106 10000   780    80    10]
 [  110  9000   770    75     9]
 [  104  8000   750    60     8]
 [  108  4000   730    40     6]
 [  101  5000   720    45     5]
 [  105  3000   710    25     4]
 [  103  2500   700    30     3]
 [  109  3500   690    28     3]
 [  102  1500   680    20     2]
 [  107  1200   650    15     1]]


In [13]:
# Q8.3: Find the indices that would sort the array by years active
years_order = banking_data[:, 4].argsort()
print(years_order)

[6 1 2 8 4 0 7 3 9 5]


In [15]:
# Q8.4: Find the customer with the second highest account balance
acc_bal_order_desc = banking_data[:,1].argsort()[::-1]
second_highest = acc_bal_order_desc[1]
customer_with_second_highest_bal = banking_data[second_highest]
print(customer_with_second_highest_bal)

[ 110 9000  770   75    9]


In [16]:
# Q8.5: Find the customer with the lowest transaction count 
order_transaction = banking_data[:,3].argsort()
lowest_tran = order_transaction[0]
customer_with_lowest_tran = banking_data[lowest_tran]
print(customer_with_lowest_tran)

[ 107 1200  650   15    1]


In [17]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 9: Mathematical Functions

# Q9.1: Calculate the absolute values of all elements
banking_data_abs = np.abs(banking_data)
print(banking_data)

[[  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]]


In [ ]:
# Q9.2: Calculate the square root of all account balances
acc_bal_sqrt_values = np.sqrt(banking_data[:,1])
print(acc_bal_sqrt_values)

# NOTES to self: 
# sqrt won't work for negative values, in real world data, neg values can be there. 

# Option 1: negatives will become 0
# balances = banking_data[:, 1]            
# safe_balances = np.maximum(balances, 0)    # elementwise max with 0
# sqrt_balances = np.sqrt(safe_balances) 


# Option 2:
# balances = banking_data[:, 1]
# sqrt_balances = np.empty_like(balances, dtype=float)  # pre-allocate once
# mask = balances >= 0
# np.sqrt(balances, out=sqrt_balances, where=mask)      # compute only on valid entries
# sqrt_balances[~mask] = np.nan                         # mark invalid as NaN (optional)

# More notes
# np.empty_like(x, dtype=..., order=...) creates a new NumPy array with the same shape 
# (and by default the same dtype) as x, but without initializing its values. That means the memory may contain 
# arbitrary “garbage” until you fill it.

# ~mask inverts the boolean array elementwise: True → False, False → True.



[ 70.71067812  38.72983346  50.          89.4427191   54.77225575
 100.          34.64101615  63.2455532   59.16079783  94.86832981]


In [21]:
# Q9.3: Calculate the square of all credit scores
credit_score_sq_values = np.square(banking_data[:,2])
print(credit_score_sq_values)

[518400 462400 490000 562500 504100 608400 422500 532900 476100 592900]


In [22]:
# Q9.4: Calculate the exponential of all transaction counts
tx_count_exp = np.exp(banking_data[:,3])
print(tx_count_exp)

[3.49342711e+19 4.85165195e+08 1.06864746e+13 1.14200739e+26
 7.20048993e+10 5.54062238e+34 3.26901737e+06 2.35385267e+17
 1.44625706e+12 3.73324200e+32]


In [23]:
# Q9.5: Calculate the natural logarithm of all account balances

# natural logarithm: 
# ln(x) is the inverse of exp: it answers “to what power should we raise e to get x?”. Defined for x > 0.

acc_bal_natural_log = np.log(banking_data[:,1])
print(acc_bal_natural_log)

[8.51719319 7.31322039 7.82404601 8.98719682 8.00636757 9.21034037
 7.09007684 8.29404964 8.16051825 9.10497986]


In [ ]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 10: Advanced Operations

# Q10.1: Calculate the cumulative sum of account balances

# Each element in the result is the sum of all previous elements (including itself).
# Useful for: running totals (like total deposits over time).
    
acc_bal_cumulative_sum = np.cumsum(banking_data[:,1])
print(acc_bal_cumulative_sum) 

[ 5000  6500  9000 17000 20000 30000 31200 35200 38700 47700]


In [26]:
# Q10.2: Calculate the cumulative product of transaction counts

# Useful in growth models (compound interest, multiplicative growth, etc.).
tran_count_cumulative_prod = np.cumprod(banking_data[:,3])
print(tran_count_cumulative_prod)


[              45              900            27000          1620000
         40500000       3240000000      48600000000    1944000000000
   54432000000000 4082400000000000]


In [ ]:
# Q10.3: Calculate the difference between consecutive account balances


# Length of result is n-1 because differences are between pairs.
# Useful for analyzing changes in balances instead of absolute balances.
acc_bal_diff = np.diff(banking_data[:,1])
print(acc_bal_diff)

[-3500  1000  5500 -5000  7000 -8800  2800  -500  5500]


In [ ]:
# Q10.4: Calculate the gradient of account balances

# estimates the rate of change at each point (like slope).
# Useful in finance for finding trends/smooth changes.

# NOTES to self:
# Study how gradient works in more depth
acc_bal_gradient = np.gradient(banking_data[:,1])
print(acc_bal_gradient)

[-3500. -1250.  3250.   250.  1000.  -900. -3000.  1150.  2500.  5500.]


In [30]:
# Q10.5: Calculate the histogram of account balances with 5 bins

# groups values into 5 ranges (bins).
# frequency distribution

# Useful for distribution analysis (e.g., how many customers fall in low/medium/high balance ranges).

hist, bin_edges = np.histogram(banking_data[:,1], bins=5)
print("Histogram:", hist)
print("Bin edges:", bin_edges)

Histogram: [3 3 1 1 2]
Bin edges: [ 1200.  2960.  4720.  6480.  8240. 10000.]


In [32]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 11: Random Numbers and Simulation

# Q11.1: Generate 6 random integers between 1 and 1000

random_integers = np.random.randint(1,1001,6)
print(random_integers)

[ 32 667  52 454  37 316]


In [ ]:
# Q11.2: Generate 6 random floats between 0 and 1

# np.random.rand(n) generates n floats in the range [0.0, 1.0).
random_floats = np.random.rand(6)
print(random_floats)

[0.26542921 0.11221377 0.58436721 0.70564079 0.21801686 0.06862469]


In [35]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

normal_dist = np.random.normal(loc=700, scale=100, size=6)
print(normal_dist)
# np.random.normal(loc, scale, size):
# loc → mean (μ = 700 here).
# scale → standard deviation (σ = 100 here).
# size=6 → 6 values.
# This simulates real-world distributions (like salaries, balances, etc.).

[522.63075876 746.3100902  686.87053648 779.64376929 661.97803287
 612.21646572]


In [36]:
# Q11.4: Shuffle the banking_data rows randomly

shuffled_banking_data = banking_data.copy()
np.random.shuffle(shuffled_banking_data)
print(shuffled_banking_data)

[[  104  8000   750    60     8]
 [  109  3500   690    28     3]
 [  103  2500   700    30     3]
 [  105  3000   710    25     4]
 [  101  5000   720    45     5]
 [  107  1200   650    15     1]
 [  106 10000   780    80    10]
 [  102  1500   680    20     2]
 [  108  4000   730    40     6]
 [  110  9000   770    75     9]]


In [38]:
# Q11.5: Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
random_numbers = np.random.rand(4)
print(random_numbers)

# np.random.seed(n) → sets the random number generator state.
# Ensures reproducibility (same random numbers every time).
# If someone else runs this with seed=123, they’ll get identical results.

[0.69646919 0.28613933 0.22685145 0.55131477]


In [39]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 12: Linear Algebra Operations

# Q12.1: Calculate the dot product of account balance and credit score columns
acc_bal = banking_data[:,1]
credit_score = banking_data[:,2]
dot_product = np.dot(acc_bal,credit_score)
print(dot_product)

35345000


In [ ]:
# Q12.2: Calculate the cross product of first two rows

# The cross product is defined only for 3-dimensional vectors
# Use cases: geometry (area of parallelogram), direction perpendicular to two vectors. In this banking context 
# it’s mostly an exercise in vector ops — cross product with banking columns has no direct business meaning unless 
# you have a defined 3D feature space.
r1 = banking_data[0,1:4]
r2 = banking_data[1,1:4]
cross_product = np.cross(r1,r2)
print(cross_product)

[ -16200  -32500 2320000]


In [ ]:
# Q12.3: Calculate the norm (magnitude) of the account balance column

# We can cast to float to avoid integer overflow in intermediate operations for very large data (good practice).
norm_acc = np.linalg.norm(acc_bal)
print(norm_acc)

17809.828747071097


In [46]:
# Q12.4: Create a 3x3 matrix and calculate its determinant

# The determinant is a scalar summarizing certain properties of a square matrix: 
# if det != 0 → matrix is invertible; det = 0 → singular (no inverse).
matr = np.random.randint(0,10,(3,3))
det_matr = np.linalg.det(matr)
print(det_matr)

-13.999999999999996


In [47]:
# Q12.5: Calculate the inverse of the 3x3 matrix
inv_matr = np.linalg.inv(matr)
print(inv_matr)

[[ 1.42857143 -0.92857143 -0.28571429]
 [ 1.28571429 -1.28571429  0.14285714]
 [-1.          1.          0.        ]]


In [ ]:
# NOTES to self:

# Types & overflow: For dot/cross/norm on potentially large numbers, prefer working with floats 
# (astype(float)) to avoid integer overflow and get consistent floating outputs.

# Cross product selection: When data rows have >3 components, explicitly pick the 3 components that are meaningful for the cross-product operation. 
# cross product on things like IDs is meaningless.

In [49]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 13: String Operations

# Q13.1: Convert all customer IDs to strings
cust_id_to_str = banking_data[:,0].astype(str)
print(cust_id_to_str)

['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [ ]:
# Q13.2: Check if any customer ID contains '100'
contains100 = cust_id_to_str.__contains__('101')
print(contains100)

# Alternative
# contains_100 = np.char.find(cust_id_to_str, '100') >= 0
# print(contains_100)       # Boolean mask
# print(np.any(contains_100))

# np.char.find(arr, '100') → returns index of substring '100' or -1 if not found.
# Comparing >= 0 gives us a boolean mask of which IDs contain '100'.
# np.any() checks if at least one element is True.


True


In [56]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
cust_id_to_str_2 = ['101a','102bc','103de','104f','105z','h106','y107','j108','k109','l110']
upper_ids = np.char.upper(cust_id_to_str_2)
print(upper_ids)

['101A' '102BC' '103DE' '104F' '105Z' 'H106' 'Y107' 'J108' 'K109' 'L110']


In [59]:
# Q13.4: Count the length of each customer ID string

# cust_len = np.char.str_len(cust_id_to_str_2)
# print(cust_len)

for i in cust_id_to_str_2:
    cust_len = np.char.str_len(i)
    print(f"{i} -> {cust_len} ")

101a -> 4 
102bc -> 5 
103de -> 5 
104f -> 4 
105z -> 4 
h106 -> 4 
y107 -> 4 
j108 -> 4 
k109 -> 4 
l110 -> 4 


In [61]:
# Q13.5: Replace '100' with 'CUST' in customer IDs

replace_id = np.char.replace(cust_id_to_str_2,'101a','CUST')
print(replace_id)

['CUST' '102bc' '103de' '104f' '105z' 'h106' 'y107' 'j108' 'k109' 'l110']


In [62]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 14: Date and Time Operations

# Q14.1: Convert years active to months
years_active = banking_data[:,4]
months_active = years_active * 12
print(months_active)

[ 60  24  36  96  48 120  12  72  36 108]


In [ ]:
# Q14.2: Calculate the average years active
avg_years_active = np.average(years_active)

# with mean
avg_years_active2 = np.mean(years_active)
print(avg_years_active2)

5.1


In [66]:
# Q14.3: Find customers who have been active for more than 5 years
cust_active_grt_5_mask = years_active > 5
cust_active_grt_5 = banking_data[cust_active_grt_5_mask,0]
print(cust_active_grt_5)

[104 106 108 110]


In [68]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_cust = np.sum(years_active)
print(total_cust)

51


In [70]:
# Q14.5: Find the customer with the shortest time active
shortest_time_active_cust = years_active.argmin() + 1
print(shortest_time_active_cust)

7


In [71]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 15: Advanced Array Operations
# Q15.1: Apply a function to calculate 5% interest on all account balances

# original + 0.05(5%) 
interest_balances = banking_data[:,1] * 1.05
print(interest_balances)

[ 5250.  1575.  2625.  8400.  3150. 10500.  1260.  4200.  3675.  9450.]


In [72]:
# Q15.2: Use np.where to categorize customers by balance ranges
bal_data = banking_data[:,1]
categories = np.where(bal_data < 4000, "LOW",
                      np.where(bal_data < 8000, "MEDIUM", "HIGH" ))
print(categories)

['MEDIUM' 'LOW' 'LOW' 'HIGH' 'LOW' 'HIGH' 'LOW' 'MEDIUM' 'LOW' 'HIGH']


In [ ]:
# Q15.3: Use np.select to categorize customers by credit score ranges
credit_scores = banking_data[:,2]
conditions = [
    (credit_scores <660),
    (credit_scores >= 660) & (credit_scores <700),
    (credit_scores >= 700) & (credit_scores <750),
    (credit_scores >= 750)
]
choices = ["POOR","FAIR","GOOD","EXCELLENT"]
score_categories = np.select(conditions,choices,default="UNKNOWN")
print(score_categories)

# NOTE to self:
# it was giving error if I didn't include  default="UNKNOWN"

['GOOD' 'FAIR' 'GOOD' 'EXCELLENT' 'GOOD' 'EXCELLENT' 'POOR' 'GOOD' 'FAIR'
 'EXCELLENT']


In [77]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
# np.piecewise applies different formulas based on conditions.

rates = [0.03, 0.04, 0.05]
conditions = [bal_data < 4000,
              (bal_data >= 4000) & (bal_data <= 8000),
              bal_data > 8000]

interest_balances_piecewise = np.piecewise(bal_data, conditions,
                                           [lambda x: x*1.03,
                                            lambda x: x*1.04,
                                            lambda x: x*1.05])
print(interest_balances_piecewise)

[ 5200  1545  2575  8320  3090 10500  1236  4160  3605  9450]


In [79]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
# np.apply_along_axis applies np.sum across each row (axis=1).

row_sums = np.apply_along_axis(np.sum, axis=1, arr=banking_data)
print(row_sums)

[ 5871  2304  3336  8922  3844 10976  1973  4884  4330  9964]


In [ ]:
# NOTES to self:
# What if columns have different datatypes?(int,str)
# Since you mixed int and str, everything becomes str (dtype <U11).
# Then np.sum will try to "add" strings → which actually concatenates them, not numeric sum.
# That’s why mixing dtypes in NumPy arrays is dangerous.

# If you want true row-wise sums with mixed dtypes, you should use Pandas DataFrame, 
# which can handle mixed types better.

In [81]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 16: Array Concatenation and Stacking
# Q16.1: Concatenate two arrays horizontally using np.hstack()

# reshape(-1, 1) -> -1 → NumPy automatically figures out the correct number of rows based on total size.
# (Here total elements = 3, so -1 becomes 3).
# 1 → means we want 1 column.

extra_col = banking_data[:,-1].reshape(-1,1)
result_h = np.hstack((banking_data, extra_col))
print(result_h.shape) 
print(result_h)

(10, 6)
[[  101  5000   720    45     5     5]
 [  102  1500   680    20     2     2]
 [  103  2500   700    30     3     3]
 [  104  8000   750    60     8     8]
 [  105  3000   710    25     4     4]
 [  106 10000   780    80    10    10]
 [  107  1200   650    15     1     1]
 [  108  4000   730    40     6     6]
 [  109  3500   690    28     3     3]
 [  110  9000   770    75     9     9]]


In [ ]:
# NOTES to self:
# Horizontal stack (hstack) → add columns side by side (like expanding width).
# Vertical stack (vstack) → add rows one below another (like expanding height).

In [82]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
result_v = np.vstack((banking_data, banking_data))
print(result_v.shape) 
print(result_v)

(20, 5)
[[  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]
 [  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]]


In [83]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
# This is a generalized version of hstack/vstack.
# Along axis=0 → stack rows (like vstack)
# Along axis=1 → stack columns (like hstack)

# axis=0 (row-wise)
concat_row = np.concatenate((banking_data, banking_data), axis=0)
print(concat_row.shape) 

# axis=1 (col-wise)
concat_col = np.concatenate((banking_data, extra_col), axis=1)
print(concat_col.shape)

(20, 5)
(10, 6)


In [87]:
# Q16.4: Stack arrays depth-wise using np.dstack()
result_d = np.dstack((banking_data, banking_data))
print(result_d.shape)

# Diffn example to understand
# A = np.array([[1,2,3],[4,5,6]])   # shape (2,3)
# B = np.array([[7,8,9],[10,11,12]])# shape (2,3)

# S = np.dstack((A, B))
# print(S.shape)      # (2, 3, 2)
# print(S[:,:,0])     # A
# print(S[:,:,1])     # B
# print(S[0,1,:])     # [2, 8]

(10, 5, 2)


In [ ]:
# Q16.5: Create a column stack using np.column_stack()

years = banking_data[:, -1]       # shape (10,) → 1D
result_c = np.column_stack((banking_data, years))
print(result_c.shape)
print(result_c)

# This is like hstack, but works even with 1D arrays (auto converts them into columns).
# hstack requires reshaping 1D arrays, but column_stack does it automatically.

(10, 6)
[[  101  5000   720    45     5     5]
 [  102  1500   680    20     2     2]
 [  103  2500   700    30     3     3]
 [  104  8000   750    60     8     8]
 [  105  3000   710    25     4     4]
 [  106 10000   780    80    10    10]
 [  107  1200   650    15     1     1]
 [  108  4000   730    40     6     6]
 [  109  3500   690    28     3     3]
 [  110  9000   770    75     9     9]]


In [90]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 17: Array Splitting Operations
# Q17.1: Split an array into 3 equal parts using np.split()

three_parts = np.split(banking_data,3)
print(three_parts)

ValueError: array split does not result in an equal division

In [92]:
# np.split strictly splits in equal parts so error

# ALternative

three_parts2 = np.array_split(banking_data,3)
print(three_parts2)

[array([[ 101, 5000,  720,   45,    5],
       [ 102, 1500,  680,   20,    2],
       [ 103, 2500,  700,   30,    3],
       [ 104, 8000,  750,   60,    8]]), array([[  105,  3000,   710,    25,     4],
       [  106, 10000,   780,    80,    10],
       [  107,  1200,   650,    15,     1]]), array([[ 108, 4000,  730,   40,    6],
       [ 109, 3500,  690,   28,    3],
       [ 110, 9000,  770,   75,    9]])]


In [ ]:
# Q17.2: Split an array at specific indices using np.split()
parts = np.split(banking_data,[3,7])
#print(parts)

for i, p in enumerate(parts, 1):
    print(f"Part {i}:\n{p}\n")

# enumerate() loops through an iterable (like list, tuple, np.array) while keeping track of the index
# By default, it starts counting from 0, but you can override it with a start value.



Part 1:
[[ 101 5000  720   45    5]
 [ 102 1500  680   20    2]
 [ 103 2500  700   30    3]]

Part 2:
[[  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]]

Part 3:
[[ 108 4000  730   40    6]
 [ 109 3500  690   28    3]
 [ 110 9000  770   75    9]]



In [96]:
# Q17.3: Split an array horizontally using np.hsplit()
# This means split columns.

parts = np.hsplit(banking_data, [2])
print("first:\n", parts[0])
print("second:\n", parts[1])

first:
 [[  101  5000]
 [  102  1500]
 [  103  2500]
 [  104  8000]
 [  105  3000]
 [  106 10000]
 [  107  1200]
 [  108  4000]
 [  109  3500]
 [  110  9000]]
second:
 [[720  45   5]
 [680  20   2]
 [700  30   3]
 [750  60   8]
 [710  25   4]
 [780  80  10]
 [650  15   1]
 [730  40   6]
 [690  28   3]
 [770  75   9]]


In [97]:
# Q17.4: Split an array vertically using np.vsplit()
top,bottom = np.vsplit(banking_data,[5])
print("Top Half:\n", top)
print("\nBottom Half:\n", bottom)

Top Half:
 [[ 101 5000  720   45    5]
 [ 102 1500  680   20    2]
 [ 103 2500  700   30    3]
 [ 104 8000  750   60    8]
 [ 105 3000  710   25    4]]

Bottom Half:
 [[  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]]


In [98]:
# Q17.5: Split an array into equal chunks using np.array_split()

parts = np.array_split(banking_data, 3)
for i, p in enumerate(parts, 1):
    print(f"Chunk {i}:\n{p}\n")

Chunk 1:
[[ 101 5000  720   45    5]
 [ 102 1500  680   20    2]
 [ 103 2500  700   30    3]
 [ 104 8000  750   60    8]]

Chunk 2:
[[  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]]

Chunk 3:
[[ 108 4000  730   40    6]
 [ 109 3500  690   28    3]
 [ 110 9000  770   75    9]]



In [99]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 18: Array Repetition and Tiling
# Q18.1: Repeat each element of an array 3 times using np.repeat()
result = np.repeat(banking_data, 3)   
print("Repeated elements of first row:\n", result)

Repeated elements of first row:
 [  101   101   101  5000  5000  5000   720   720   720    45    45    45
     5     5     5   102   102   102  1500  1500  1500   680   680   680
    20    20    20     2     2     2   103   103   103  2500  2500  2500
   700   700   700    30    30    30     3     3     3   104   104   104
  8000  8000  8000   750   750   750    60    60    60     8     8     8
   105   105   105  3000  3000  3000   710   710   710    25    25    25
     4     4     4   106   106   106 10000 10000 10000   780   780   780
    80    80    80    10    10    10   107   107   107  1200  1200  1200
   650   650   650    15    15    15     1     1     1   108   108   108
  4000  4000  4000   730   730   730    40    40    40     6     6     6
   109   109   109  3500  3500  3500   690   690   690    28    28    28
     3     3     3   110   110   110  9000  9000  9000   770   770   770
    75    75    75     9     9     9]


In [ ]:
# Q18.2: Repeat an entire array 2 times using np.tile()
result = np.tile(banking_data,(2,1))
print("Dataset repeated 2 times (row-wise):\n", result)

# np.tile(A, reps)
# A → input array
# reps → number of repetitions for each axis
# If reps is a single integer, it repeats along the last axis (columns).
# If reps is a tuple (m, n):
# m → repeat along rows (vertical stacking, downwards)
# n → repeat along columns (horizontal stacking, side by side)

Dataset repeated 2 times (row-wise):
 [[  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]
 [  101  5000   720    45     5]
 [  102  1500   680    20     2]
 [  103  2500   700    30     3]
 [  104  8000   750    60     8]
 [  105  3000   710    25     4]
 [  106 10000   780    80    10]
 [  107  1200   650    15     1]
 [  108  4000   730    40     6]
 [  109  3500   690    28     3]
 [  110  9000   770    75     9]]


In [103]:
# Q18.3: Repeat a 2D array using np.tile()
result = np.tile(banking_data,2)
print("Dataset repeated 2 times:\n", result)

Dataset repeated 2 times:
 [[  101  5000   720    45     5   101  5000   720    45     5]
 [  102  1500   680    20     2   102  1500   680    20     2]
 [  103  2500   700    30     3   103  2500   700    30     3]
 [  104  8000   750    60     8   104  8000   750    60     8]
 [  105  3000   710    25     4   105  3000   710    25     4]
 [  106 10000   780    80    10   106 10000   780    80    10]
 [  107  1200   650    15     1   107  1200   650    15     1]
 [  108  4000   730    40     6   108  4000   730    40     6]
 [  109  3500   690    28     3   109  3500   690    28     3]
 [  110  9000   770    75     9   110  9000   770    75     9]]


In [104]:
# Q18.4: Create a pattern using np.tile()

# repeat first 3 customer IDs, 4 times
pattern = np.tile(banking_data[:3, 0], 4)   
print("Pattern of Customer IDs:\n", pattern)

Pattern of Customer IDs:
 [101 102 103 101 102 103 101 102 103 101 102 103]


In [105]:
# Q18.5: Repeat elements with different counts using np.repeat()
ids = banking_data[:5, 0]   # first 5 customer IDs
counts = [1, 2, 3, 4, 5]  # repeat times
result = np.repeat(ids, counts)
print("Customer IDs repeated differently:\n", result)

Customer IDs repeated differently:
 [101 102 102 103 103 103 104 104 104 104 105 105 105 105 105]


In [ ]:
# (Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active)
# [[  101  5000   720    45     5]
#  [  102  1500   680    20     2]
#  [  103  2500   700    30     3]
#  [  104  8000   750    60     8]
#  [  105  3000   710    25     4]
#  [  106 10000   780    80    10]
#  [  107  1200   650    15     1]
#  [  108  4000   730    40     6]
#  [  109  3500   690    28     3]
#  [  110  9000   770    75     9]]

# Question 19: Array Comparison and Logical Operations
# Q19.1: Compare two arrays for equality using np.array_equal()
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 4])

print("a vs b:", np.array_equal(a, b)) 
print("a vs c:", np.array_equal(a, c)) 

# Returns True if arrays have the same shape and same elements.

a vs b: True
a vs c: False


In [111]:
# Q19.2: Check if arrays are close using np.allclose()
# Returns True if arrays are element-wise equal within a tolerance (good for floating point comparison).

x = np.array([1.0, 2.0, 3.000001])
y = np.array([1.0, 2.0, 3.0])

print("Are x and y close? -> ", np.allclose(x, y))

Are x and y close? ->  True


In [112]:
# Q19.3: Apply logical AND operation between arrays

# np.logical_and(arr1, arr2) → Performs element-wise AND.
# Works like: True if both elements are non-zero (or True).
p = np.array([True, False, True])
q = np.array([True, True, False])

print(np.logical_and(p, q))

[ True False False]


In [ ]:
# Q19.4: Apply logical OR operation between arrays

# np.logical_or(arr1, arr2) → Performs element-wise OR.
# Works like: True if at least one is non-zero (or True).
print(np.logical_or(p, q))

[ True  True  True]


In [114]:
# Q19.5: Apply logical NOT operation to an array

# np.logical_not(arr) → Inverts truth values.
# For numbers: 0 → True, nonzero → False.
print(np.logical_not(p, q))

[False  True False]


In [124]:
# Question 20: Array Set Operations
# Q20.1: Find unique elements in an array using np.unique()

a = np.array([6, 1,2,2,2, 3, 4, 5, 6,6])
unique_a = np.unique(a)
print(unique_a)

[1 2 3 4 5 6]


In [125]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
b = np.array([2,3,4, 5, 6,6, 7, 8, 9])
intersection = np.intersect1d(a,b)
print(intersection)

[2 3 4 5 6]


In [126]:
# Q20.3: Find the union of two arrays using np.union1d()
#Combination of both arrays, without duplicates.
union = np.union1d(a, b)
print("Union:", union)

Union: [1 2 3 4 5 6 7 8 9]


In [127]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
# np.setdiff1d(a, b) → returns elements in a that are not in b.
diff = np.setdiff1d(a, b)
print("Elements in a but not in b:", diff)

Elements in a but not in b: [1]


In [ ]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()

# np.setxor1d(a, b) → returns elements present in either a or b but not both
# Keeps non-common elements only.
sym_diff = np.setxor1d(a, b)
print("Symmetric Difference:", sym_diff)

Symmetric Difference: [1 7 8 9]
