[Store ID, Sales, Customers, Inventory, Returns]

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])


# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

In [2]:
import numpy as np

retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

# 1. What is the **total revenue** generated across all stores?



[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [3]:
retail_data[:,1].sum()

np.int64(335000)

In [5]:
# 2. Which store recorded the **highest sales**?

retail_data[:,1].argmax()+1

np.int64(9)

In [6]:
# 3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [7]:
# 4. What is the **average daily sales** per store?

retail_data[:,1].mean()

np.float64(33500.0)

In [8]:
# 5. How many stores achieved sales **above ₹35,000**?

sum(retail_data[:,1] > 35000)

np.int64(3)

In [ ]:
# 6. Which store had the **highest customer footfall**?

retail_data[:, 2].argmax() + 1

np.int64(9)

In [12]:
#  7. What is the **average number of customers** per store?

retail_data[:, 2].mean()

np.float64(425.0)

In [13]:
# 8. How many stores have **more than 450 customers**?

sum(retail_data[:,2] > 450)

np.int64(3)

In [14]:
# 9. Which store has the **lowest customer count**?
retail_data[:, 2].argmin() + 1

np.int64(1)

In [15]:
# 10. Is there any store where **high sales do not correspond to high customers**?

sales = retail_data[:, 1]
customers = retail_data[:, 2]

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)

# Find stores with high sales but low customers
stores = retail_data[(sales > avg_sales) & (customers < avg_customers), 0]
print(stores)

[5]


In [16]:
# 11. What is the **total inventory** across all stores?

sum(retail_data[:,3])

np.int64(14300)

In [17]:
# 12. Which store has the **highest inventory stock**?
retail_data[:, 3].argmax() + 1

np.int64(9)

In [18]:
# 13. How many stores have **inventory less than 1300 units**?
sum(retail_data[:,3] < 1300)

np.int64(3)

In [22]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
# retail_data[:, 4].argmax() + 1
returns = retail_data[:, 4]
inventory = retail_data[:, 3]

return_rates = returns / inventory
np.argmax(return_rates) + 1

np.int64(9)

In [24]:
# 15. Which stores have **returns greater than 15 units**?

retail_data[retail_data[:,4] > 15 , 0]

array([4, 7, 9])

In [33]:
# 16. Is there a **positive correlation** between sales and customers?

# Positive correlation means that when one variable increases, the other also tends to increase.

sales = retail_data[:,1]
customers = retail_data[:,2]

corr_matrix = np.corrcoef(sales,customers)
print(corr_matrix)

# Extract the correlation value (off-diagonal) bcz diagnol are alwyas 1

# [ correlation(sales, sales)     correlation(sales, customers) ]
# [ correlation(customers, sales) correlation(customers, customers) ]
correlation = corr_matrix[0, 1]

print(f"Correlation between sales and customers: {correlation:.2f}")

if(correlation>0):
    print("There is a positive correlation.")
elif correlation < 0:
    print("There is a negative correlation.")
else:
    print("No correlation.")

[[1.         0.95936369]
 [0.95936369 1.        ]]
Correlation between sales and customers: 0.96
There is a positive correlation.


In [37]:
# 17. Which store has **high customer visits but low sales**?

customers = retail_data[:,2]
sales = retail_data[:,1]

avg_customers = customers.mean()
avg_sales = sales.mean()

stores_with_highCustomer_And_lowSales = retail_data[(customers > avg_customers) & (sales < avg_sales),0 ]
print(stores_with_highCustomer_And_lowSales)

[2]


In [38]:
# 18. Which store has **low customers but high sales**?

sales = retail_data[:, 1]
customers = retail_data[:, 2]

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)

# Find stores with high sales but low customers
stores_with_highSales_And_lowCustomers = retail_data[(sales > avg_sales) & (customers < avg_customers), 0]
print(stores)

[5]


In [41]:
# 19. How many stores have **sales per customer above ₹90**?

sum((retail_data[:,1] / retail_data[:,2]) > 90)


np.int64(0)

In [44]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

customers = retail_data[:,2]
inventory = retail_data[:,3]

avg_customers = customers.mean()
avg_inventory = inventory.mean()

stores_with_lowCustomers_highInventory = retail_data[(customers < avg_customers) & (inventory > avg_inventory),0]
print(stores_with_lowCustomers_highInventory)

[10]


In [47]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
profits = retail_data[:,1] * 0.2
print(profits)

[5000. 6400. 5600. 8200. 7000. 5400. 7800. 6000. 9000. 6600.]


In [49]:
# 22. Which store has the **highest profit**?

np.argmax(profits)+1

np.int64(9)

In [50]:
# 23. Which store has the **lowest profit**?
np.argmin(profits)+1

np.int64(1)

In [ ]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?


new_sales = retail_data[:,1] + retail_data[:,1] * 0.1
print(new_sales)

[27500. 35200. 30800. 45100. 38500. 29700. 42900. 33000. 49500. 36300.]


In [55]:
# 25. How will **total profit** change with the 10% sales increase?
old_profit = retail_data[:, 1].sum() * 0.20
print(f"old profit: {old_profit}")

new_profit = new_sales.sum() * 0.20
print(f"new profit: {new_profit}")

profit_change = new_profit - old_profit
print("Profit Change:", profit_change)


old profit: 67000.0
new profit: 73700.0
Profit Change: 6700.0


In [57]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
# Not Clear!!!

sales = retail_data[:, 1]
inventory = retail_data[:, 3]

sales_per_unit = sales / inventory
print(sales_per_unit)
threshold = np.percentile(sales_per_unit, 75)  # top 25% in ratio
print(threshold)
restock_stores = retail_data[sales_per_unit > threshold, 0]

print("Stores needing urgent restock:", restock_stores)

[20.83333333 21.33333333 25.45454545 25.625      25.         20.76923077
 22.94117647 24.         25.         22.75862069]
25.0
Stores needing urgent restock: [3 4]


In [60]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?

# return percentage = returns per sales into 100

sales = retail_data[:, 1]
returns = retail_data[:, 4]

return_percentage = returns/sales
print(return_percentage)

threshold = np.percentile(return_percentage,75)
print(threshold)

quality_checks_store = retail_data[return_percentage > threshold,0]
print(quality_checks_store)

[0.0004     0.00046875 0.00028571 0.0004878  0.00034286 0.00033333
 0.00046154 0.00046667 0.00055556 0.00033333]
0.00046822916666666665
[2 4 9]


In [62]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?

# Using Min-Max normalization, where min value becomes 0, and max value becomes 1

# formula -> (X - Xmin) / (Xmax - Xmin)

sales = retail_data[:,1]

customers = retail_data[:,2]

inventory = retail_data[:,3]

inventory_turnover = sales / inventory

# Normalize all metrics (0–1 range)
sales_norm = (sales - sales.min()) / (sales.max() - sales.min())
customers_norm = (customers - customers.min()) / (customers.max() - customers.min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

overall_score = sales_norm + customers_norm + turnover_norm
print(overall_score)

retail_data[np.argmax(overall_score),0]


[0.01320132 1.06617162 1.43489649 2.6        1.85128713 0.34
 1.86729179 1.31534653 2.87128713 1.24969614]


np.int64(9)

In [63]:
# 29. Which store is the **worst performer overall**?

retail_data[np.argmin(overall_score),0]

np.int64(1)

In [65]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?

sales = retail_data[:, 1]
customers = retail_data[:, 2]
print(sales)
print(customers)

avg_sales = np.mean(sales)
avg_customers = np.mean(customers)
print(avg_sales)
print(avg_customers)

retail_data[(sales > avg_sales) & (customers > avg_customers),0]



[25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]
[300 450 380 500 420 360 480 400 550 410]
33500.0
425.0


array([4, 7, 9])